"""add_returns_to_orders

Revision ID: afdac6dbe826
Revises: 16c7041ecc55
Create Date: 2026-07-27 07:49:51.959213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afdac6dbe826'
down_revision: Union[str, Sequence[str], None] = '16c7041ecc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('returns', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'returns')
    # ### end Alembic commands ###
